version: "3.8"
services:
  postgresql:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    networks:
      - sample-network
networks:
  sample-network:
    name: sample-network
